{
 "title": "Nxpod / Components / spicedb",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Requests by Status [1m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{job=\"spicedb\"}[1m])) by (grpc_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_server_handling_seconds_bucket{job=\"spicedb\"}[5m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{job=\"spicedb\"}[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  { "title": "Datastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Garbage Collection [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(spicedb_datastore_gc_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(spicedb_datastore_gc_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Query Latency [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(spicedb_datastore_query_latency_bucket[5m])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(spicedb_datastore_query_latency_bucket[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "New database connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(spicedb_datastore_mysql_connect_count_total[1m])) by (success)",
     "legendFormat": "success: {{success}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Cache Hit & Miss Rates [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum (increase (spicedb_cache_hits_total[$__rate_interval]))",
     "legendFormat": "Hit"
    },
    {
     "expr": "sum (increase (spicedb_cache_misses_total[$__rate_interval]))",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "Cache Hit/Miss Ratio [1m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum (increase (spicedb_cache_hits_total[$__rate_interval])) / sum (increase (spicedb_cache_misses_total[$__rate_interval]))",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Check Request Consistency [1m] (client reported)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase (gitpod_spicedb_requests_check_total[$__rate_interval])) by (consistency)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}