{
 "title": "Nxpod / Component / agent-smith",
 "tags": [ "gitpod-mixin" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"agent-smith.*\"}, node)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{cluster=~\"$cluster\", node=~\"$node\", pod=~\"agent-smith.*\"}, pod)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Agent-Smith metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Classifier Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(gitpod_agent_smith_classifier_commandline_blocklist_hit_total{cluster=~\"$cluster\"})) by (cluster)",
     "legendFormat": "{{cluster}} - Commandline Hits"
    },
    {
     "expr": "sum(rate(gitpod_agent_smith_classifier_signature_signature_hit_total{cluster=~\"$cluster\"})) by (cluster)",
     "legendFormat": "{{cluster}} - Signature Hits"
    }
   ]
  },
  {
   "title": "Penalty attempts",
   "type": "timeseries",
   "description": "This panel represents the number of penalties that Agent-Smith is trying to apply per second.\n\nIt represents attempts and may not reflect the exact number of penalties applied, please check for error logs or slack messages to be sure if penalties are indeed applied.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(gitpod_agent_smith_penalty_attempts_total{cluster=~\"$cluster\"}[5m])) by (cluster, penalty)",
     "legendFormat": "{{cluster}} - {{penalty}}"
    },
    {
     "expr": "sum(rate(gitpod_agent_smith_penalty_attempts_failed_total{cluster=~\"$cluster\"})) by (cluster, penalty)",
     "legendFormat": "{{cluster}} - failed ⚠️  {{penalty}}"
    }
   ]
  },
  {
   "title": "Classification Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(gitpod_agent_smith_classifier_signature_process_miss_total{cluster=~\"$cluster\"})) by (cluster, classifier_name)",
     "legendFormat": "{{cluster}} - Signature Process Miss {{ classifier_name }}"
    },
    {
     "expr": "sum(rate(gitpod_agent_smith_classifier_commandline_allowlist_hit_total{cluster=~\"$cluster\"})) by (cluster, classifier_name)",
     "legendFormat": "{{cluster}} - Allowlist Hits {{ classifier_name }}"
    }
   ]
  },
  {
   "title": "Egress Violations",
   "type": "timeseries",
   "description": "This panel represents the number of egress violations that Agent Smith found.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (severity,cluster) (gitpod_agent_smith_egress_violations_total)",
     "legendFormat": "{{cluster}} - {{severity}}"
    }
   ]
  },
  {
   "title": "Classification Backpressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(gitpod_agent_smith_classification_backpressure_in_count{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}} - In Pressure"
    },
    {
     "expr": "sum(gitpod_agent_smith_classification_backpressure_out_count{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}} - Out Pressure"
    },
    {
     "expr": "sum(rate(gitpod_agent_smith_classification_backpressure_in_drop_total{cluster=~\"$cluster\"})) by (cluster)",
     "legendFormat": "{{cluster}} - Classification Drop Rate"
    }
   ]
  },
  {
   "title": "Proc Index Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(gitpod_agent_smith_procfs_detector_index_size{cluster=~\"$cluster\"}) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Signature Cache Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(gitpod_agent_smith_procfs_detector_cache_use_total{cluster=~\"$cluster\", use=\"miss\"}[5m])) by (cluster) / sum(rate(gitpod_agent_smith_procfs_detector_cache_use_total{cluster=~\"$cluster\"}[5m])) by (cluster)) * 100",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Workspace Difference",
   "type": "timeseries",
   "description": "Difference between workspaces found by agent-smith and workspaces ws-manager knows about",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{cluster=~\"()\", phase=\"Running\", type=\"Regular\"})  by (cluster) - on (cluster) sum(gitpod_agent_smith_procfs_detector_workspace_count{cluster=~\"()\"}) by (cluster)",
     "legendFormat": "Difference"
    }
   ]
  },
  { "title": "Pod Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Container image version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "kube_pod_container_info{cluster=~\"$cluster\", pod=~\"$pod\", image=~\".+\", container=\"agent-smith\"}",
     "legendFormat": "{{cluster}} - {{image}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Cores being used"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "description": "Saturation > 100% means that the container is requesting more than its limits.\n\nKubernetes will start to throttle CPU when that happens. That's a sign of degraded performance.\n\n'No Data' indicates that the pod has no CPU limits.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{container!=\"POD\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits_cpu_cores{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node} - {{pod}} - CPU Saturation"
    },
    {
     "expr": "sum(\nrate(container_cpu_cfs_throttled_seconds_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod)",
     "legendFormat": "{{pod}} - CPU Throttles"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "description": "Memory can't be throttled. When a container reaches 100% of its memory limits,  Kubernetes will kill the container and restart it.\n\n'No Data' indicates that the pod doesn't have Memory limits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\nrate(container_memory_working_set_bytes{container!=\"POD\", container!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)\n/\nsum(\n  kube_pod_container_resource_limits{container!=\"POD\", cluster=\"$cluster\", pod=~\"$pod\", resource=\"memory\"}\n) by (pod, cluster, node)\n",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Memory Saturation"
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_bytes_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_bytes_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Network Saturation (Packets Dropped)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Receive"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_packets_dropped_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "Errors/s" }
   ],
   "targets": [
    {
     "expr": "sum (\n  rate(container_network_receive_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Received"
    },
    {
     "expr": "sum (\n  rate(container_network_transmit_errors_total{container!=\"POD\", pod!=\"\", cluster=~\"$cluster\", node=~\"$node\", pod=~\"$pod\"}[1m])\n) by (pod, cluster, node)",
     "legendFormat": "{{cluster}} - {{node}} - {{pod}} - Transmitted"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kube_pod_container_status_restarts_total{cluster=~\"$cluster\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{cluster}} - {{kubernetes_pod_node_name}} - {{pod}} "
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_running{cluster=~\"$cluster\", pod=~\"$pod\"} == 1 ",
     "legendFormat": "{{pod}}  - RUNNING"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_terminated{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_terminated_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{pod}}  - TERMINATED -> {{reason}}"
    },
    {
     "expr": "(\n  sum by (pod) (kube_pod_container_status_waiting{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n) * on(pod) group_left(reason) (\n  sum by (pod, reason) (kube_pod_container_status_waiting_reason{cluster=~\"$cluster\", pod=~\"$pod\"}) == 1\n)",
     "legendFormat": "{{pod}}  - WAITING -> {{reason}}"
    }
   ]
  },
  {
   "title": "Replicas availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{cluster=~\"$cluster\", deployment=\"agent-smith\"}",
     "legendFormat": "{{cluster}} - {{deployment}} - Desired"
    },
    {
     "expr": "kube_deployment_status_replicas_available{cluster=~\"$cluster\", deployment=\"agent-smith\"}",
     "legendFormat": "{{cluster}} - {{deployment}} - Available replicas"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{cluster=~\"$cluster\", deployment=\"agent-smith\"}",
     "legendFormat": "{{cluster}} - {{deployment}} - Unvailable replicas"
    }
   ]
  },
  {
   "title": "Go Runtime Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", job=\"agent-smith\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage (as seen by the runtime process)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{cluster=~\"$cluster\", job=\"agent-smith\", pod=~\"$pod\"}[5m])",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_sys_bytes{cluster=~\"$cluster\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Allocation rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total{cluster=~\"$cluster\", pod=~\"$pod\"}[5m])",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_goroutines{cluster=~\"$cluster\", job=\"agent-smith\", pod=~\"$pod\"}",
       "legendFormat": "{{cluster}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Garbage collection time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"agent-smith\", pod=~\"$pod\", quantile=\"0.5\"}",
       "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 50th percentile"
      },
      {
       "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"agent-smith\", pod=~\"$pod\", quantile=\"0.75\"}",
       "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 75th percentile"
      },
      {
       "expr": "go_gc_duration_seconds{cluster=~\"$cluster\", job=\"agent-smith\", pod=~\"$pod\", quantile=\"1\"}",
       "legendFormat": "{{cluster}} - {{pod}} - GC Duration - 100th percentile"
      }
     ]
    }
   ]
  }
 ]
}