{
 "title": "[Example] Nxpod Self-hosted / Overview",
 "tags": [ "gitpod-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Running Workspaces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_phase_total{phase=\"Running\"}) by (type)",
     "legendFormat": "{{ type }}"
    },
    {
     "expr": "sum(gitpod_ws_manager_mk2_workspace_activity_total{active=\"false\"})",
     "legendFormat": "Pending workspaces"
    }
   ]
  },
  {
   "title": "Workspace Failures per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(gitpod_ws_manager_mk2_workspace_stops_total{reason=\"failed\"}[5m])\n) by (cluster, type)\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Regular Workspace Startup time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "sum(rate(gitpod_ws_manager_mk2_workspace_startup_seconds_bucket{type=\"Regular\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}